FROM python:3.11.1-slim-buster

# C:\Users\Andre\Desktop\Проекты\PycharmProjects\RDC
WORKDIR /PycharmProjects/RDC/RDC

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update && \
    apt-get install -y --no-install-recommends gcc

COPY ./requirements.txt .
RUN pip install -r requirements.txt

COPY . .