# Generated by Django 4.2.4 on 2023-08-28 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patients',
            old_name='birthDate',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='birthDate',
            new_name='birth_date',
        ),
        migrations.RemoveField(
            model_name='users',
            name='phone',
        ),
    ]
