# Generated by Django 4.2.4 on 2023-08-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='birth_date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='users',
            name='birth_date',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
