# Generated by Django 4.2.4 on 2023-09-11 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0006_alter_requests_doctor_alter_requests_research'),
        ('user', '0002_rename_birthdate_patients_birth_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctors',
        ),
    ]
