# Generated by Django 4.2.4 on 2023-09-12 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_delete_doctors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='first_name',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='patients',
            name='last_name',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='patients',
            name='patronymic',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
