# Generated by Django 4.2.4 on 2023-09-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_patients_first_name_alter_patients_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='Passport',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='patients',
            name='birth_date',
            field=models.DateField(blank=True, default='2000-01-01'),
        ),
    ]
