# Generated by Django 4.2.4 on 2023-09-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_patients_passport_alter_patients_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_doctor',
            field=models.BooleanField(default=0),
        ),
    ]
