# Generated by Django 4.2.4 on 2023-09-25 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor_cabinet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Researches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_file', models.FileField(upload_to='researches/')),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=1)),
                ('request_data', models.DateField(auto_now_add=True)),
                ('request_time', models.TimeField(auto_now_add=True)),
                ('payment_data', models.DateField(default='2000-01-01')),
                ('doctor', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='doctor_cabinet.doctors')),
            ],
        ),
    ]
