# Generated by Django 4.2.4 on 2023-09-25 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('treatment', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor_cabinet', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.patients'),
        ),
        migrations.AddField(
            model_name='requests',
            name='report',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='doctor_cabinet.report'),
        ),
        migrations.AddField(
            model_name='requests',
            name='research',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='treatment.researches'),
        ),
        migrations.AddField(
            model_name='requests',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.services'),
        ),
        migrations.AddField(
            model_name='requests',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
