# Generated by Django 4.2.4 on 2023-08-27 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('treatment', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='doctor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='user.doctors'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='patient',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='user.patients'),
        ),
    ]
