# Generated by Django 4.2.4 on 2023-09-30 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor_cabinet', '0002_initial'),
        ('treatment', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researches',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requests',
            name='doctor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='doctor_cabinet.doctors'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='research',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='treatment.researches'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.services'),
        ),
    ]
