# Generated by Django 4.2.4 on 2023-08-23 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_patients_birth_date_alter_users_birth_date'),
        ('treatment', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='patient',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.CASCADE, to='user.patients'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='payment_data',
            field=models.DateTimeField(default='2000-01-01'),
        ),
    ]
