# Generated by Django 4.2.4 on 2023-09-09 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0004_requests_request_time_alter_requests_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researches',
            name='request',
        ),
        migrations.AddField(
            model_name='requests',
            name='research',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='treatment.researches'),
        ),
        migrations.AlterField(
            model_name='researches',
            name='research_file',
            field=models.FileField(upload_to='media/'),
        ),
    ]
