# Generated by Django 4.2.4 on 2023-09-11 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_cabinet', '0001_initial'),
        ('treatment', '0005_remove_researches_request_requests_research_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='doctor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='doctor_cabinet.doctors'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='research',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='treatment.researches'),
        ),
    ]
