# Generated by Django 4.2.4 on 2023-09-12 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0006_alter_requests_doctor_alter_requests_research'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='request_data',
            field=models.DateField(auto_now_add=True),
        ),
    ]
