# Generated by Django 4.2.4 on 2023-09-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0007_alter_requests_request_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='doctors_coment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='payment_data',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
