version: '3.8'

services:
  web:
    build: .
    command: gunicorn RDC.asgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env